services:
  db:
    image: postgres:15.7
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      TZ: 'Asia/Seoul' # 시간대를 한국 표준시로 설정
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
      - ./docker/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres-data-dev: